## NumPy Array
NumPy (Numerical Python) is a fundamental library for numerical computation in Python. It provides functions to operate matrices and multi-dimensional arrays efficiently, as well as mathematical functions for linear algebra, Fourier analysis, and more. Many other libraries are built on top of NumPy, such as SciPy (for scientific computing), Pandas (for data manipulation and analysis), and scikit-learn (for machine learning).

The most important object defined in NumPy is an N-dimensional array type called `ndarray`. It describes a collection of elements of the same type, which can be accessed using a zero-based index. The shape of an array is a tuple of integers representing the size of the array along each dimension (called **axis**).

![](./images/numpy_array_shape.png)

The data type of each array elements is an instance of `dtype` object. The following table shows different scalar data types defined in NumPy.
| Data type | Description |
| --------- | ----------- |
| `int_` | Plateform-defined `int` (usually `int32`) |
| `float_` | Plateform-defined `float` (usually `float64`) |
| `complex_`  | Built-in Python `complex` (`complex128`) |
| `int8`    | Integer -128 to 127 |
| `int16`   | Integer -32768 to 32767 |
| `int32`   | Integer -2147483648 to 2147483647 |
| `int64`   | Integer -9223372036854775808 to 9223372036854775807 |
| `uint8`    | Unsigned integer 0 to 255 |
| `uint16`   | Unsigned integer 0 to 65535 |
| `uint32`   | Unsigned integer 0 to 4294967295 |
| `uint64`   | Unsigned integer 0 to 18446744073709551615 |
| `float32`   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa |
| `float64`   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa |
| `complex64`   | Complex number represented by two 32-bit floats (real and imaginary components) |
| `complex128`  | Complex number represented by two 64-bit floats (real and imaginary components) |

In [36]:
import math
import numpy as np
import matplotlib.pyplot as plt

In [24]:
## Create 1D array
arr1d = np.array([1,2,3,4])    # Define array given all elements
arr1d = np.arange(1, 10, 3)    # arange(start, end, step): from start to end (exclusive) with step size
arr1d = np.linspace(0, 1, 11)  # linspace(start, end, n): from start to end (inclusive) n linearly spaced points
arr1d = np.repeat(np.arange(5), 2)  # Repeat each element of an array after themselves

print(arr1d)

[0 0 1 1 2 2 3 3 4 4]


In [29]:
## Create 2D array
arr2d = np.array([[1,2,3], [4,5,6]])  # Define array given all elements
arr2d = np.zeros((2,3))  # Create array of zero
arr2d = np.ones((2,3))   # Create array of one
arr2d = np.zeros((2,3), dtype=np.int8)  # Cast a specific dtype
arr2d = np.arange(12).reshape(3,4)      # By default numpy array is row-major
arr2d = np.eye(3) - 0.2*np.eye(3, k=1)  # eye() create a diagonal matrix of one, k=1 specifies the 1st upper diagonal
arr2d = np.diag([3,4,5]) + np.diag([1,2], k=-1)  # diag() create a diagonal matrix of given elements
arr2d = np.tile(np.arange(4), (3,1))    # Construct an array by repeating array a certain number of times along each axes
arr2d = np.row_stack([np.arange(4)]*3)  # Construct an array by stacking rows
arr2d = np.column_stack([np.arange(3)+i for i in range(4)])  # Construct an array by stacking columns

print(arr2d)
print("The number of axes (dimensiona) of the array:", arr2d.ndim)
print("The size of the array in each dimension:", arr2d.shape)
print("The total number of elements in the array:", arr2d.size)
print("The data type of the elements in the array:", arr2d.dtype)
print("The size in bytes of each elements in the array:", arr2d.itemsize)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]
The number of axes (dimensiona) of the array: 2
The size of the array in each dimension: (3, 4)
The total number of elements in the array: 12
The data type of the elements in the array: int32
The size in bytes of each elements in the array: 4


In [ ]:
## Create 3D array
img1 = np.random.rand(3,4)  # Uniformly distributed random number between 0 and 1
img2 = np.random.rand(3,4)
arr3d = np.stack([img1, img2], axis=2)  # Stack arrays along specified axis
arr3d = np.concatenate([img1[:,:,np.newaxis], img2[:,:,np.newaxis]], axis=2)  # Concatenate arrays along specified existing axis
print(arr3d.shape)

(3, 4, 2)


## Arithmetic operations
NumPy provides several arithmetic operations that are performed element-wise on arrays. These inculde addition `+`, subtraction `-`, multiplication `*`, division `/`, and power `**`. When two arrays of different shapes are used, broadcasting will align their shapes according to some rules.

<img src="./Images/broadcasting.png" width="600"/>

In [ ]:
res = np.arange(3) + 5
res = np.ones((3,3), dtype=int) + np.arange(3)
res = np.arange(3).reshape((3,1)) + np.arange(3)
print(res)

A = np.array(np.arange(6).reshape((2,3)))
print(A**2)

[[0 1 2]
 [1 2 3]
 [2 3 4]]
[[ 0  1  4]
 [ 9 16 25]]


## Linear Algebra
To perform matrix-vector and matrix-matrix multiplication, use the operator `@`. 

In [51]:
def rotation_matrix(degree):
    theta = math.radians(degree)
    R = np.array([[math.cos(theta), -math.sin(theta)],
                  [math.sin(theta), math.cos(theta)]])
    return R

R1 = rotation_matrix(30)
R2 = rotation_matrix(60)
print(R1)
print(R2)
print(R1 @ R2)  # or R1.dot(R2)

[[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]
[[ 0.5       -0.8660254]
 [ 0.8660254  0.5      ]]
[[ 2.22044605e-16 -1.00000000e+00]
 [ 1.00000000e+00  2.22044605e-16]]


In [ ]:
A = np.array([[0,-1],[1,0]])
print(A)
print("Transpose:")  
print(A.T)  # or A.transpose()
print("Inverse:")
print(np.linalg.inv(A))
print("Determinant:", np.linalg.det(A))
print("L2 norm:", np.linalg.norm(A))  # That is np.sqrt(np.sum(A**2))
print("A squared:")
print(A @ A)  # Matrix product, diffrent from A**2 element-wise multiplication!

D, V = np.linalg.eig(A)
## V[:,i] is the normalized eigenvector corresponding to the eigenvalue D[i]
print("Eigen values:", D)

[[ 0 -1]
 [ 1  0]]
Transpose:
[[ 0  1]
 [-1  0]]
Inverse:
[[ 0.  1.]
 [-1. -0.]]
Determinant: 1.0
L2 norm: 1.4142135623730951
A squared:
[[-1  0]
 [ 0 -1]]
Eigen values of the matrix: [0.+1.j 0.-1.j]
